Feature/volume viewer
GalaxyHunters/VIVID3D pull request #296
Opened 2022-10-30 16:30 UTC by Beilinson

2022-10-30 19:11 UTC, NaftaliD requested changes

2022-10-30 19:11 UTC, NaftaliD commented on vivid3d.egg-info/PKG-INFO
> +Classifier: License :: OSI Approved :: BSD License
didn't we get rid of this?

the entire vivid3d.egg-info

2022-10-31 16:04 UTC, Beilinson commented on CMakeLists.txt
These are things that are otherwise default on, and we don't need them.

2022-10-31 16:06 UTC, Beilinson commented on CMakeLists.txt
> +        src/Utils/Noisify.h)
in the rest of the stuff we always include cpp files and not headers, so I'm not sure

2022-10-31 16:13 UTC, NaftaliD commented on CMakeLists.txt
oh ok

2022-10-31 16:13 UTC, Beilinson commented on lib/ImportAndExport/AssimpImportExport.cpp
>              Assimp::Exporter exp;
it should probably be void as if theres an error I throw the error and dont return anything

2022-10-31 16:14 UTC, Beilinson commented on lib/ImportAndExport/FbxCode.cpp
>  #include "Decimate.h"
definitely

2022-10-31 16:14 UTC, Beilinson commented on src/ModelBuilder/VoronoiVolume.cpp
> -void CVoronoiVolume::CreateSurface()
runs on init, no reason to run it manually

2022-10-31 16:14 UTC, NaftaliD commented on CMakeLists.txt
> +        src/Utils/Noisify.h)
yeah, that's what I said, only CPP files need to be written unless its an inline h file.

2022-10-31 16:15 UTC, Beilinson commented on vivid3d.egg-info/PKG-INFO
> +Classifier: License :: OSI Approved :: BSD License
yeah the gitignore isn't working no clue why

2022-10-31 18:32 UTC, merged